- name: Push to Hugging Face Spaces
  env:
    HF_TOKEN: ${{ secrets.HF1_TOKEN }}
  run: |
    git remote set-url origin https://huggingface.co/spaces/AkashVD26/pdfsense
    git config --global user.name "Akashvarma26"
    git config --global user.email "akashvdatla@gmail.com"
    git push https://AkashVD26:${HF_TOKEN1}@huggingface.co/spaces/AkashVD26/pdfsense main
