name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Configure Git
        run: |
          git config --global user.name "Akashvarma26" # Your GitHub username
          git config --global user.email "akashvdatla@gmail.com" # Your GitHub email

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN1: ${{ secrets.HF_TOKEN1 }}
        run: |
          git remote add huggingface https://AkashVD26:${HF_TOKEN1}@huggingface.co/spaces/AkashVD26/pdfsense.git
          git push huggingface main
